spring:
  data:
    mongodb:
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
