spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8060

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    product-url: http://localhost:8091/api/v1/products
    # payment-url
